img_length: 256

network:
  node_extraction:
    input_channels: 1
    output_channels: 3
  graph_extraction:
    input_channels: 3
    output_channels: 1

data_path: /graphics/scratch/schuelej/sar/data/256
save_path: /graphics/scratch/schuelej/sar/data/256/results

validation_fraction: 0.1
batch_size: 16

use_small_dataset: false
max_files: null # integer if above is true, else null