project: node_extraction
entity: salehah


# run details
run_name: unet_16f
resume: true
run_id: 3ee26r9o
run_type: training


parameters:
  # training params
  train_imgs: null
  epochs: 200
  batch_size: 16
  # model params
  n_filters: 16
  depth: 5

sweep_config: null