project: node_extraction
entity: salehah


# run details
run_name: b_16_d1
resume: true
run_id: 81xmypwq
run_type: training


parameters:
  # training params
  train_imgs: null
  epochs: 200
  batch_size: 16
  # model params
  n_filters: 16
  depth: 1

sweep_config: null