project: node_extraction
entity: salehah


# run details
run_name: unet_4f
resume: true
run_id: 91pmt9xd
run_type: training


parameters:
  # training params
  train_imgs: null
  epochs: 200
  batch_size: 16
  # model params
  n_filters: 4
  depth: 5

sweep_config: null
