project: edge_extraction
entity: salehah


# run details
run_name: edge_nn
resume: false
run_id: null
run_type: training


model_filename: model.h5


parameters:
  batch_size: 4
  node_pairs_in_batch: 8
  n_filters: 16
  n_conv2_blocks: 2
  n_conv3_blocks: 3
  epochs: 100


sweep_config: null