project: node_extraction
entity: salehah


# run details
run_name: b_16_d2
resume: true
run_id: pqphq89g
run_type: training


parameters:
  # training params
  train_imgs: null
  epochs: 200
  batch_size: 16
  # model params
  n_filters: 16
  depth: 2

sweep_config: null