project: node_extraction
entity: salehah


# run details
run_name: baseline
resume: true
run_id: 1izhg74a
run_type: training


parameters:
  # training params
  train_imgs: 2000
  epochs: 200
  batch_size: 16
  # model params
  n_filters: 64
  depth: 5

sweep_config: null