project: node_extraction
entity: salehah


# run details
run_name: baseline_ss
resume: false
run_id: null
run_type: training


parameters:
  # training params
  train_imgs: null
  epochs: 200
  batch_size: 16
  # model params
  n_filters: 64
  depth: 5

sweep_config: null