project: edge_extraction
entity: salehah


# run details
run_name: vgg_mod_a
resume: true
run_id: wcxdtu93
run_type: training


parameters:
  epochs: 100
  learning_rate: 1e-5
  batch_size: 8
  node_pairs_in_batch: 4
  n_filters: 8
  n_conv2_blocks: 2
  n_conv3_blocks: 3

sweep_config: null
